export const ART_STYLES = [
    { value: "3D Render", label: "3D Render" },
    { value: "Analog Film", label: "Analog Film" },
    { value: "Anime", label: "Anime" },
    { value: "Cinematic", label: "Cinematic" },
    { value: "Comic Book", label: "Comic Book" },
    { value: "Digital Art", label: "Digital Art" },
    { value: "Enhance", label: "Enhance" },
    { value: "Fantasy Art", label: "Fantasy Art" },
    { value: "Isometric", label: "Isometric" },
    { value: "Line Art", label: "Line Art" },
    { value: "Low Poly", label: "Low Poly" },
    { value: "Modeling Compound", label: "Modeling Compound" },
    { value: "Neon Punk", label: "Neon Punk" },
    { value: "Origami", label: "Origami" },
    { value: "Photographic", label: "Photographic" },
    { value: "Pixel Art", label: "Pixel Art" },
    { value: "Realism", label: "Realism" },
    { value: "Sketch", label: "Sketch" },
    { value: "Sticker", label: "Sticker" },
    { value: "Watercolor", label: "Watercolor" },
];